FROM python:3.9

COPY main.py main.py
COPY fibonacci.py fibonacci.py

RUN mkdir artifacts

RUN apt-get update
RUN apt-get install -y texlive graphviz graphviz-dev python3-pygraphviz
RUN pip install networkx
RUN pip install matplotlib
RUN pip install pygraphviz

RUN pip install -i https://test.pypi.org/simple/ ast-builder-from-fib==2.0

RUN python3.9 main.py
RUN pdflatex artifacts/my_tex.tex


#  _______________________
# < Dockerfiles are cool! >
#  -----------------------
#         \   ^__^
#          \  (oo)\_______
#             (__)\       )\/\
#                 ||----w |
#                 ||     ||